### ISSUE TITLE
Crackling Noise During Airplay Playback

### ISSUE THREAD

**Issue by abht234** [JohannVR/JohannVRs-Home-Assistant-Addons#4]
Connected [This](https://www.amazon.com/Decoder-PCM2704-Analog-HiFi-Level-Coaxial/dp/B08KWC81S6) PCM2704 USB DAC to the Home Assistant host and linked it via an optical cable to a soundbar. The card was immediately recognized by Home Assistant, and music is played through Airplay. However, there are crackling noises during playback, and I cannot identify the source.

Tested the USB Sound Card and optical cable by connecting them to a laptop and audio was clear without any crackling noises. Is this a problem with the Airplay add-on, or could it be related to codecs or drivers?

**Comment by JohannVR** [comment]
I don't really know why there are crackling noises, maybe you could try to install the official shairport-sync program on a test device and check if the crackling persists. There is a docker image available, which might make it easier to install. If it's gone, then I can try to look further into it, but right now I don't really think it's a problem with the add-on.

**Comment by abht234** [comment]
Thanks for your reply, it turned out to be related to the default bitrate of Pulse Audio, which is set to 44100Hz. After changing it to 48000Hz the problem disappeared.

**Comment by JohannVR** [comment]
Great! Glad to hear you could fix it! :)
